# fly.toml app configuration file generated for sparkling-wave-9745 on 2023-08-15T15:35:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sparkling-wave-9745"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
